### ISSUE TITLE
CSV formatting compatibility

### ISSUE THREAD

**Issue by PaulMcInnis** [uwaft/Data-Collection-App#6]
In the CSV![image](https://cloud.githubusercontent.com/assets/3189865/20573931/265b85ac-b180-11e6-8875-7fe9e740da7d.png) 
Change the format of time from MM:SS to a counter which counts the number of seconds elapsed (parsing trouble)

**Comment by taipingli** [comment]
Changed log to seconds, Testing with MATLAB required.
